name: Register Slash Commands

on:
  push:
    branches:
      - main

jobs:
  register-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run register-commands script
        run: npx ts-node register-commands.ts
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
